//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wiki.Resources.Views {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringsUtilisateurs {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringsUtilisateurs() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Wiki.Resources.Views.StringsUtilisateurs", typeof(StringsUtilisateurs).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contenu.
        /// </summary>
        public static string ArticleContenu {
            get {
                return ResourceManager.GetString("ArticleContenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date de modification.
        /// </summary>
        public static string ArticleDateModification {
            get {
                return ResourceManager.GetString("ArticleDateModification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titre.
        /// </summary>
        public static string ArticleTitre {
            get {
                return ResourceManager.GetString("ArticleTitre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;ancien mot de passe ne correspond pas à votre mot de passe actuel.
        /// </summary>
        public static string ErreurAncienMDP {
            get {
                return ResourceManager.GetString("ErreurAncienMDP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le nom d&apos;utilisateur et le mot de passe ne correspondent pas.
        /// </summary>
        public static string ErreurConnexion {
            get {
                return ResourceManager.GetString("ErreurConnexion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Courriel déjà utilisé.
        /// </summary>
        public static string ErreurCourriel {
            get {
                return ResourceManager.GetString("ErreurCourriel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modèle non-valide.
        /// </summary>
        public static string ErreurModel {
            get {
                return ResourceManager.GetString("ErreurModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom d&apos;utilisateur déjà utilisé.
        /// </summary>
        public static string ErreurUtilisateur {
            get {
                return ResourceManager.GetString("ErreurUtilisateur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connexion.
        /// </summary>
        public static string TitreConnexion {
            get {
                return ResourceManager.GetString("TitreConnexion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inscription.
        /// </summary>
        public static string TitreInscription {
            get {
                return ResourceManager.GetString("TitreInscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modification du mot de passe.
        /// </summary>
        public static string TitreModifierMDP {
            get {
                return ResourceManager.GetString("TitreModifierMDP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profil de l&apos;utilisateur.
        /// </summary>
        public static string TitreProfil {
            get {
                return ResourceManager.GetString("TitreProfil", resourceCulture);
            }
        }
    }
}
