//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wiki.Resources.Views {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringsShared {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringsShared() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Wiki.Resources.Views.StringsShared", typeof(StringsShared).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Article.
        /// </summary>
        public static string Article {
            get {
                return ResourceManager.GetString("Article", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voulez-vous créér cet article?.
        /// </summary>
        public static string ArticleCreer {
            get {
                return ResourceManager.GetString("ArticleCreer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;article est inexistant..
        /// </summary>
        public static string ArticleInexistant {
            get {
                return ResourceManager.GetString("ArticleInexistant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bienvenue!.
        /// </summary>
        public static string Bienvenue {
            get {
                return ResourceManager.GetString("Bienvenue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retour à l&apos;accueil.
        /// </summary>
        public static string BoutonAccueil {
            get {
                return ResourceManager.GetString("BoutonAccueil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Créer.
        /// </summary>
        public static string BoutonCreer {
            get {
                return ResourceManager.GetString("BoutonCreer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Éditer.
        /// </summary>
        public static string BoutonEditer {
            get {
                return ResourceManager.GetString("BoutonEditer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effacer.
        /// </summary>
        public static string BoutonEffacer {
            get {
                return ResourceManager.GetString("BoutonEffacer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sauvegarder.
        /// </summary>
        public static string BoutonSauvegarder {
            get {
                return ResourceManager.GetString("BoutonSauvegarder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmer.
        /// </summary>
        public static string Confirmer {
            get {
                return ResourceManager.GetString("Confirmer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connexion au compte.
        /// </summary>
        public static string ConnexionCompte {
            get {
                return ResourceManager.GetString("ConnexionCompte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Création de compte.
        /// </summary>
        public static string CreationCompte {
            get {
                return ResourceManager.GetString("CreationCompte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Éditer l&apos;article.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Êtes-vous sûr que vous désirez effacer cet article?.
        /// </summary>
        public static string Effacer {
            get {
                return ResourceManager.GetString("Effacer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom de l&apos;article:.
        /// </summary>
        public static string FormRechercher {
            get {
                return ResourceManager.GetString("FormRechercher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soumettre la requête.
        /// </summary>
        public static string FormSubmit {
            get {
                return ResourceManager.GetString("FormSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez entrer le nom de l&apos;article que vous désirez consulter. Vous pouvez également sélectionner un article dans le menu de gauche..
        /// </summary>
        public static string Intro {
            get {
                return ResourceManager.GetString("Intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contenu.
        /// </summary>
        public static string LabelContenu {
            get {
                return ResourceManager.GetString("LabelContenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contributeur.
        /// </summary>
        public static string LabelContributeur {
            get {
                return ResourceManager.GetString("LabelContributeur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date de la dernière modification.
        /// </summary>
        public static string LabelDateModification {
            get {
                return ResourceManager.GetString("LabelDateModification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Révision no.
        /// </summary>
        public static string LabelRevision {
            get {
                return ResourceManager.GetString("LabelRevision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titre.
        /// </summary>
        public static string LabelTitre {
            get {
                return ResourceManager.GetString("LabelTitre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retourner à l&apos;accueil.
        /// </summary>
        public static string LienAccueil {
            get {
                return ResourceManager.GetString("LienAccueil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connexion.
        /// </summary>
        public static string LienConnexion {
            get {
                return ResourceManager.GetString("LienConnexion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Créer un article.
        /// </summary>
        public static string LienCreer {
            get {
                return ResourceManager.GetString("LienCreer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Déconnexion.
        /// </summary>
        public static string LienDeconnexion {
            get {
                return ResourceManager.GetString("LienDeconnexion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effacer.
        /// </summary>
        public static string LienEffacer {
            get {
                return ResourceManager.GetString("LienEffacer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inscription.
        /// </summary>
        public static string LienInscription {
            get {
                return ResourceManager.GetString("LienInscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string LienLangue {
            get {
                return ResourceManager.GetString("LienLangue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-CA.
        /// </summary>
        public static string LienLangueParam {
            get {
                return ResourceManager.GetString("LienLangueParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifier.
        /// </summary>
        public static string LienModifier {
            get {
                return ResourceManager.GetString("LienModifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifier le mot de passe.
        /// </summary>
        public static string LienModifierMDP {
            get {
                return ResourceManager.GetString("LienModifierMDP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profil.
        /// </summary>
        public static string LienProfil {
            get {
                return ResourceManager.GetString("LienProfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifier le mot de passe.
        /// </summary>
        public static string ProfilMDP {
            get {
                return ResourceManager.GetString("ProfilMDP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profil de l&apos;utilisateur.
        /// </summary>
        public static string ProfilUtilisateur {
            get {
                return ResourceManager.GetString("ProfilUtilisateur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TABLE DES MATIÈRES.
        /// </summary>
        public static string TDM {
            get {
                return ResourceManager.GetString("TDM", resourceCulture);
            }
        }
    }
}
